AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

# Parameters are CloudFormation features to pass input
# to your template when you create a stack
Parameters:
    TrafficShiftType:
        Type: String

Resources:
  DDBToES:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: DDBToES.handler
      Runtime: nodejs8.10
      CodeUri: ../
      Description: ''
      MemorySize: 3008
      Timeout: 300
      Role: 'arn:aws:iam::885426109155:role/LambdaExecute'
      FunctionName: DDBToES
      Environment:
        Variables:
          DDB_TABLE_NAME: AT_ATCLAIM_EXT
          DEBUG_LOG: 'true'
          ES_ENDPOINT: >-
            https://search-es-ltcm1-tst-lowb5m353nbpxjilhrwhfkn5zu.ap-northeast-2.es.amazonaws.com
          ES_INDEX_PREFIX: at_atclaim_ext
          ES_REGION: ap-northeast-2
          ES_DOC: GD_GOODS_QNA
          LAMBDA_FUNC_NAME: DDBToES
          RemainingTimeInMillis: '20000'
          DATE_FIELD: RGST_DTTM,MODI_DTTM
          KEY_FIELD1: PartitionKey
          KEY_FIELD2: SortKey(nullable)

      AutoPublishAlias: live
      DeploymentPreference:
       Type: !Ref TrafficShiftType #Canary10Percent10Minutes, Linear10PercentEvery1Minute
